version: "3"
services:
  client:
    container_name: react-socket-io-app_client
    build:
      context: ./client
      dockerfile: Dockerfile
    image: piotrmackiewicz/express-react-dockerized_client
    ports:
      - ${CLIENT_PORT}:3000
    volumes:
      - ./client:/client
      - /client/node_modules
    depends_on:
      - server
    networks:
      - react-socket-io-app-network
  server:
    container_name: react-socket-io-app_server
    build:
      context: ./server
      dockerfile: Dockerfile
    image: piotrmackiewicz/express-react-dockerized_server
    ports:
      - ${SERVER_PORT}:5000
    volumes:
      - ./server:/server
      - /server/node_modules
    networks:
      - react-socket-io-app-network

networks:
    react-socket-io-app-network:
        driver: bridge